# Generated by Django 3.0.4 on 2020-03-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200325_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_name',
            field=models.CharField(max_length=98, unique=True),
        ),
    ]
